### ISSUE TITLE
Can compiled it on Windows？

### ISSUE THREAD

**Issue by wanghai1988** [birgander2/PyRAT#11]

**Comment by birgander2** [comment]
Technically, yes, of course. However, I mainly use Linux and my Windows box at work has no compiler. I would be glad to hear if there are problems or not.

In any case you can run PyRAT also without compiling directly from the directory. In that case, some functionality will be missing, but most is there.

**Comment by wanghai1988** [comment]
when I run "python steup.py install" ,the error “Runtime Error” 
![kvgilht92czx1mt3rb__1ga](https://user-images.githubusercontent.com/13306286/31040251-87d7d764-a5b7-11e7-8052-8398e82478cf.png)
Occurred；and then console print error msg “ERROR: GDAL is required to run PyRAT. Please install requirements (see README.md) and try again !” ！

**Comment by birgander2** [comment]
As the error message says: You need to install the gdal package in your python distribution. This is needed to run PyRAT. And also some others, have a look in README.md and requirements.yml.

**Comment by birgander2** [comment]
And as a side note, you can also enter the PyRAT main directory and launch pyrat.run directly (i.e. without installing via setup.py). However, the package requirements need still to be fullfilled.
