### ISSUE TITLE
ModuleNotFoundError: No module named 'pyrat.filter.Filter'

### ISSUE THREAD

**Issue by GoogolRen** [birgander2/PyRAT#17]
There is no Filter.py in the filter folder either repo or my downloaded codes. While when I run the command
$ python setup.py install
this module is needed. Is there anyone who met the same trouble?

**Comment by birgander2** [comment]
You're right!!! No idea why this file(s) got lost in the last sync. I'll add them now!

**Comment by birgander2** [comment]
Have been on my disc, but not in the repo. I don't understand that. Hopefully, there are no more of such problems, if yes, please let me know!
