### ISSUE TITLE
Add support for headless/jupyter notebook usage

### ISSUE THREAD

**Issue by whatnick** [birgander2/PyRAT#18]
PyRAT is pretty closely coupled with PyQT4 as such difficult to extract specific algorithms and run them in Jupyter notebooks. It would be great to decouple PyQT4 (only import it in GUI modules) and allow usage in headless mode.

![image](https://user-images.githubusercontent.com/491396/72975801-89830a80-3e25-11ea-898d-7cb7a088f4cb.png)

**Comment by birgander2** [comment]
Good point, but I think this should work already. In fact, PyQt is imported only in the GUI modules). The individual workers of PyRAT do not depend on PyQt, so as long as you only use the batch interface, PyRAT should run in a Jupyter notebook.

Something like
```
import pyrat
pyrat.load.rat("vv.rat")
pyrat.filter.boxcar()
```
In fact, I even managed to start the GUI (`pyrat.show()`) without any problems. I seems I don't understand yet the problems you have. Very likely it is required to have PyQt5 at least installed. Why this is problematic?

**Comment by whatnick** [comment]
I have not yet successfully installed pyrat in my Jupyter Hub environment. Will keep experimenting. However the point I am trying to make is that the import path should not make PyQT5 a dependency in batch mode. Hence perhaps a refactor to delay import PytQT5 in GUI modules in needed.

**Comment by whatnick** [comment]
I am attempting a similar setup locally in WSL (Windows way to get Linux working). However this is alos headless and the close coupling to Qt is giving be breakage. I will attempt a bandaid fix to catch this.

![image](https://user-images.githubusercontent.com/491396/73132415-e1608200-406e-11ea-9957-818c50763103.png)

**Comment by whatnick** [comment]
There is good news. I have `import pyrat` working in jupyter on WSL.
![image](https://user-images.githubusercontent.com/491396/73140442-0d125500-40cd-11ea-8a5b-28cc83078623.png)

To get here I had to: 
- Make my headless environment have a display , run an Xserver and `export DISPLAY=0:0` to point WSL to it.
![image](https://user-images.githubusercontent.com/491396/73140464-4e0a6980-40cd-11ea-8f91-4b2cd6eed7cd.png)
- Correct a typo in RyRAT source [here](https://github.com/birgander2/PyRAT/blob/2b70d15b4ea20f43c193c9083efcac1e9d454aa0/pyrat/filter/Math.py#L1)
- Install `libfftw3-dev` in Ubuntu 18.04 to compile binaries.
- Install as documented in README.md

To get more consistent install behaviour and catch typos and such I propose integrating a CI environment such as [circleci](https://circleci.com/) which takes a clean Ubuntu 18.04 docker image and attempts to run some batch mode processing on every merge to master. Let me know what you think and I will set this up and make a pull request. I am also familiar with Travis CI , or I can use the recent Github Actions.

**Comment by birgander2** [comment]
I see. So your point is that pyqt5 is only imported when the gui is actually used and not when only the batch mode is working. That makes sense. However, I didn't encountered any problems up to now - out of curiosity: why exactly importing pyqt5 is problematic for headless operation? In practice, I almost never use the gui mode.

**Comment by whatnick** [comment]
The PyQt5 headless breaks the build as shown in the WSL screenshot a few comments up, due to invoking the Qt5Agg backend in matplotlib somewhere along the way. I found other references to this issue and some workarounds. My approach was to not make it headless, however alternative approaches to bypass this `importerror` exist. Which would be to fix up the reference to `Qt5Agg` in `Unweight.py` and continue past the import error.

**Comment by whatnick** [comment]
I have started on the CI implementation as promised. Build is still broken due to PyQt5 vagaries. You can see latest iteration [here](https://app.circleci.com/jobs/github/whatnick/PyRAT/4).

**Comment by whatnick** [comment]
The PR for CI support is now open and users can be directed to the script to show working install of PyRAT on fresh systems and also catch any errors in PyRAT code.

**Comment by whatnick** [comment]
As noted above I have a working notebook with PyRAT [here](https://github.com/whatnick/dea-notebooks/blob/feat/sara_slc/Frequently_used_code/SARA_SLC_Download.ipynb), hoping to have increases PyRAT usage in Australia.

**Comment by birgander2** [comment]
Very good to hear that. Thanks for all the inputs. I hope I'll find the time to work again on PyRAT soon and to integrate your suggestions.

**Comment by birgander2** [comment]
The Unweight.py module is broken, or better, has never worked in the intendend way (added by a colleague while learning how to program PyRAT). I can probably remove it entirely - I'll talk to him asap.

**Comment by birgander2** [comment]
Note: At least using newer PyQt5 versions should be possible now.

**Comment by whatnick** [comment]
For people looking at scripting using PyRAT sample notebook is [here](https://docs.dea.ga.gov.au/notebooks/Frequently_used_code/SARA_SLC_download.html).
