### ISSUE TITLE
Improve Cython install using setup.py

### ISSUE THREAD

**Issue by whatnick** [birgander2/PyRAT#19]
Improve distribution of PyRAT with cython calls in `setup.py`.

Recommendations fro cython docs [here](https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#distributing-cython-modules).

**Comment by birgander2** [comment]
What do you mean exactly? Currently we use cythonize() which works well for me.

**Comment by whatnick** [comment]
The recommendation basically calls for shipping generated .c files and using those by default if not use cython commandline option is specified during install.


> This simply means that the setup.py file that you ship with will just be a normal distutils file on the generated .c files, for the basic example we would have instead:

This approach can also be used to ship windows specific .c files and conditionally compile them with MSVC and support that platform as well. Cythonize is only invoked if user has cython installed and explicitly calls for it.

**Comment by birgander2** [comment]
I tried to fix this. Should compile now as described above. Hopefully ;-)
