### ISSUE TITLE
Avoid same file/path names distinguishable only by letter case

### ISSUE THREAD

**Issue by mxmn** [birgander2/PyRAT#2]
Scenario:
Mac user with case insensitive filesystem (e.g. mac provided by org/corp), will not be able to have "pyrat" and "PyRat"/"PyRAT" in the same directory.

**Comment by birgander2** [comment]
Really? Welcome to 21st century, Apple... Ok, I'll change that next week, assuming that you already have fixed it somehow locally. General recommodation: I use Anaconda Python 3.5 on both Linux and Windows. On Windows I didn't manage to run the cython compiler, but everything is build in a way that it works even without (but slower).

**Comment by birgander2** [comment]
Changed to "pyrat.run"
