### ISSUE TITLE
problem about create environment 

### ISSUE THREAD

**Issue by 2016276144** [birgander2/PyRAT#24]
![image](https://user-images.githubusercontent.com/43675392/81409611-f9699680-9171-11ea-8025-f809672b8988.png)
can't create environmnet at windows ,need help

**Comment by birgander2** [comment]
Take care of captitalisation of filenames in Windows (it's not "Requirements.txt" but "requirements.txt", and probably better use the _win Version.). This one works for me:
`conda env create -f requirements_win.txt -n pyrat`. If in doubt, please google a bit about how to manage conda environments.
