### ISSUE TITLE
Add QGis support

### ISSUE THREAD

**Issue by birgander2** [birgander2/PyRAT#6]
Not clear yet what to do exactly - have to find a QGis user who uses its Python interface...

**Comment by birgander2** [comment]
Note: QGis seems to still use Python2, while PyRAT is already on Python3. This makes it tricky to develop an interface. Probably we have to wait for QGis 3.

**Comment by birgander2** [comment]
Note: QGIS 3 will be based on Python 3

**Comment by whatnick** [comment]
Hi, jumping in from QGIS standpoint. This interface will really help delegate the visualization components to QGIS and let PyRAT focus on the SAR algorithms.

**Comment by birgander2** [comment]
In fact, we already have a working plugin for QGIS. I'll add it to the repo soon. However, it's a bit tricky to install, as both QGIS and PyRAT need to run in the same Python environment (and most QGIS installations include their own 'locked' Python). Are you interested in testing?

**Comment by whatnick** [comment]
This would be awesome. Definitely interested in testing. Perhaps the plugin
has to mature to use the QGIS plugin mechanism and PyRAT has to mature to
be published on PyPI and be pip installable as a dependency of the plugin.
Perhaps answers here will help:

https://gis.stackexchange.com/questions/196002/development-of-a-plugin-which-depends-on-an-external-python-library


Always worth starting a public discussion as I am sure this is a challenge
many plugin developers face.

**Comment by birgander2** [comment]
The colleague who implemented the QGIS plugin will be back in January. I think it makes sense waiting for him with testing, because personally I don't understand well the interfacing. Thanks for the link, this will help. Up to now we have to use a QGIS installed though Anaconda Python (conda), which is far from ideal.

**Comment by whatnick** [comment]
I am back from the holidays and doing some fire analysis using Sentinel-1. Looking forward to being able to use more of PySAR functionality. Perhaps in Jupyter notebooks as well as QGIS. The PyQT4 dependencies make it difficult to install in notebooks. Will create a separate issue around that.

**Comment by birgander2** [comment]
I'm also back now ;-) I'm planning to add the QGIS modules next week - looking forward for some feedback!

**Comment by lixfel** [comment]
The QGIS plugin PyRATBridge is now included into the repository. The installation instructions for the plugin can be found under qgis/README.md.

**Comment by tobbcode** [comment]
I really like the idea of using pyrat as a plugin for QGis. 
I tried to install it and after changing the path in the setup .sh line 27 to ```cp -r $PyRAT/pyrat ~/anaconda3/envs/$envname/lib/python3.7/site-packages/pyrat``` (which is the default anaconda install directory for new installations) If you don't want to hard code it you can get the path to the environment quite easily with ```conda env``` list and regex or ```conda activate envname``` and ```which python```
 
When I import a rat file using the plugin everything seems to work, but I can't get QGis to show the data of the layer. 
The import of F-SAR data via import airborne crashes with the following error:

> Original exception was:
>Traceback (most recent call last):
>  File "/home/tobias/.local/share/QGIS/QGIS3/profiles/default/python/plugins/PyRATBridge/mainPlugin.py", line 74, in <lambda>
    PyRATBridge.menuAction(self, pyratTool))
  File "/home/tobias/.local/share/QGIS/QGIS3/profiles/default/python/plugins/PyRATBridge/mainPlugin.py", line 144, in menuAction
    doc=pyratTool.__doc__)
  File "/media/processing/Repos/tikgit_pyrat/pyrat/viewer/Dialogs.py", line 17, in __init__
    line.addWidget(QtWidgets.QLabel(para['text']))
KeyError: 'text'

**Comment by lixfel** [comment]
When you import the rat file, is it a geocoded rat file?
If not, QGIS won't be able to show the layer.
You can check if it's a geocoded rat file by exporting the rat file with ENVI-Header (.hdr) and check the ENVI-Header for valid geocoding.
QGIS can only read raster layers from files and PyRATBridge doesn't know what a PyRAT-Worker does.
That's you are prompted to save the layer as rat file after the import for the transfer to QGIS.

I will change the installation script to remove the hardcoded path, thanks for the advice.
The F-SAR import issue is a little bit more tricky, I will try to find a workaround soon.

**Comment by lixfel** [comment]
Importing of F-SAR data with the F-SAR import should now be possible.
I've improved the setup.sh to get the right anaconda directory, too.
